
name: Azure Deploy - Terraform & Functions

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Package Functions
        run: |
          chmod +x build_functions.sh
          ./build_functions.sh


      - name: Deploy Functions (zip deploy)
        env:
          AZURE_FUNCTIONAPP_NAME_INGEST: ${{ secrets.AZURE_FUNCTIONAPP_NAME_INGEST }}
          AZURE_FUNCTIONAPP_NAME_REPORT: ${{ secrets.AZURE_FUNCTIONAPP_NAME_REPORT }}
        run: |
          az functionapp deployment source config-zip --name $AZURE_FUNCTIONAPP_NAME_INGEST --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --src ingest_function.zip
          az functionapp deployment source config-zip --name $AZURE_FUNCTIONAPP_NAME_REPORT --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --src report_function.zip
